sudo: required

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:nerdboy/embedded
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated build-essential

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo apt-get install libnanomsg-dev

# command to run tests, e.g. python setup.py test
script: LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib python setup.py test
